### ISSUE TITLE
Is there a Spanish version?

### ISSUE THREAD

**Issue by kikemadrigal** [plattysoft/Modern-MSX-BASIC-Game-Dev#1]
it's a nice resource

**Comment by plattysoft** [comment]
I was not expecting this request to come this way :-D, maybe MSX.org or Twitter.
A spanish version is not planned at the moment. Maybe I'll do it in the future, but no guarantees. in any case it would take me no less than a couple of months to translate it.
And I would like to do it myself, being spanish and all.
